spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:\Users\kicinskim\OneDrive\JAVA\kodzik\todo-app\todo-db'
  jpa:
    hibernate:
      ddl-auto: validate
management:
  endpoints:
    web:
      exposure:
        exclude:
          include: '*'
server:
  error:
    include-message: always